#!/usr/bin/env bash
#This script transfers a file from client
#to server

args=("$@")
if [ $# -lt 4 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	scp -o StrictHostKeyChecking=no -i "${args[3]}" "${args[0]}" "${args[2]}@${args[1]}":~
fi
