#!/usr/bin/env bash
# This script installs nginx on web-01

apt-get update
apt-get install -y nginx
service nginx stop
mv /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak
mkdir -p /etc/nginx/html
touch /etc/nginx/html/index.html
echo "Hello World!" >> /etc/nginx/html/index.html
touch /etc/nginx/html/404.html
echo "Ceci n'est pas une page" >> /etc/nginx/html/404.html
echo "server {
	listen 80 default_server;
	listen [::]:80 default_server;

	root /etc/nginx/html;
	index index.html index.htm index.nginx-debian.html;

	location /redirect_me {
		return 301 www.mcdevinc.tech;
	}
	error_page 404 /404.html;
	location /404 {
		root /etc/nginx/html;
		internal;
	}
}" >> /etc/nginx/sites-available/default
service nginx start
