#!/usr/bin/env bash
# This installs and configure HAproxy
#+ on lb01 server

apt-get update
apt-get install -y haproxy
echo "ENABLED=1" >> /etc/default/haproxy
bash -c 'cat << EOF > /etc/haproxy/haproxy.cfg
global
        daemon
        maxconn 256
defaults
        mode http
        timeout connect 5000ms
        timeout client 50000ms
        timeout server 50000ms

frontend web-frontend
        bind *:80
        mode http
        default_backend web-backend

backend web-backend
        balance roundrobin
        server 61777-web-01 54.236.53.9:80 check
        server 61777-web-02 54.90.20.128:80 check

listen stats
        bind *:8080
        mode http
        option forwardfor
        option httpclose
        stats enable
        stats show-legends
        stats refresh 5s
        stats uri /stats
EOF'

systemctl enable haproxy
systemctl start haproxy
