#!/usr/bin/env bash
# This script configure container to
#+ nginx must run as nginx user
#+ nginx must listen on all active ip on port 8080

sed -i "s/#user ww-data/user nginx/" /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
pkill apache2
chmod 744 /etc/nginx/nginx.conf
sudo service nginx stop
sudo -u nginx service nginx start
